name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install PDM
        run: pip install pdm
      - name: Install dependencies
        run: pdm install -G :all
      - name: Run tests
        run: pdm run pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install PDM
        run: pip install pdm
      - name: Install dependencies
        run: pdm install -G :all
      - name: Run black
        run: pdm run black --check .
      - name: Run flake8
        run: pdm run flake8 .
      - name: Run mypy
        run: pdm run mypy .